### ISSUE TITLE
 reader ExecuteDataReaderAsync 方法 读取为空数据抛异常

### ISSUE THREAD

**Issue by arezl** [fs7744/DataAccess#12]
目前采取两种方式解决为空数据 Reader问题，使用有点复杂， 
方法一>代码里面可以用 IsDBNull(int ordinal)方法先进行判断   
`if (!reader.IsDBNull(reader.GetOrdinal("MiddleName")))     
  Console.Write(" {0}", reader.GetString(reader.GetOrdinal("MiddleName")));`
方法二>数据库sql查询 进行 isnull判断处理   

希望能进行封装

**Comment by fs7744** [comment]
添加https://github.com/fs7744/DataAccess/blob/master/src/VIC.DataAccess/Extensions/DataRecordHelper.cs
